### ISSUE TITLE
Wrong path to "Posts" in navigation

### ISSUE THREAD

**Issue by FQ400** [ertuil/erblog#10]
I installed the theme and played with it.
The path to "Posts" is wrong. It should be `/posts` instead of `/post`.

<img width="801" alt="Screenshot 2020-04-01 at 14 05 20" src="https://user-images.githubusercontent.com/451298/78135397-1fd53d00-7422-11ea-8150-5295ff79641a.png">

https://github.com/ertuil/erblog/blob/e90862125b681557ef644618fc71d36f9bd21326/layouts/partials/nav.html#L14

**Comment by ertuil** [comment]
It could be fixed by rename `content/posts` to `content/post` in your filesystem.

**Comment by FQ400** [comment]
Thank you.
