### ISSUE TITLE
Support for Disqus

### ISSUE THREAD

**Issue by lloydroc** [ertuil/erblog#11]
Hello Can we please add support for Disqus?

**Comment by ertuil** [comment]
We do not support Disqus yet, but there are two hooks designed for any comment systems. It is possible to create a new file `layouts/partials/self-define-single.html` and insert any javascript codes. For more information, please refer [here](https://github.com/ertuil/erblog#4-self-define-html-hook).

Thus, there are two possible ways to add support for Disqus easily with `self-define-single.html`:

1. Use internal Disqus support from Hugo. Just insert `{{ template "_internal/disqus.html" . }}` into `self-define-single.html`. [Hugo documents about Disqus ](https://gohugo.io/content-management/comments/#add-disqus) tells what you need to do.

2. Directly copy any code from Disqus and insert in `self-define-single.html`.

**Comment by lloydroc** [comment]
Thanks, that works for me. It would be nice to have this in the documents somewhere?
