### ISSUE TITLE
Tags URL Missing Slash

### ISSUE THREAD

**Issue by lloydroc** [ertuil/erblog#13]
On the main page it lists all the tags and categories and you can click on them. The URL that is rendered has a trailing `/` so the server doesn't have to 301 back to `/index.html`. This is good. However, on the index pages for the tags they don't get rendered correctly. They need a trailing `/`.

See [here](https://lloydrochester.com/tags/signal-processing/). For each of the posts the `signal-processing` tag next to the date the url is `https://lloydrochester.com/tags/signal-processing` and should be `https://lloydrochester.com/tags/signal-processing/`. It's making the server 301.

I'm on commit `e90862125b681557ef644618fc71d36f9bd21326`.

Thanks.

**Comment by ertuil** [comment]
fixed
