### ISSUE TITLE
Question about turning off disqus commenting from about page

### ISSUE THREAD

**Issue by averyrobbins1** [ertuil/erblog#16]
Awesome theme! I am very new to Hugo, and I am using your theme for my personal website. I just had a quick question about disqus comments with your theme. I was able to follow your instructions on the readme by inserting `{{ template "_internal/disqus.html" . }}` in the self-define-single.html, and my disqus short name in the congif.toml.

Is there a way to turn off the commenting for the about page or to only have commenting available on each post? I think it really only makes sense to have commenting on things like posts and similar content. Hope my question makes sense. Again, awesome theme. I am enjoying it.

**Comment by ertuil** [comment]
```
{{ if ne .Permalink "<urls of your about page>" }}
    {{ template "_internal/disqus.html" . }}
{{ end }}
```
That might help

**Comment by ertuil** [comment]
I am wondering if you have solved this problem? 
If you have any further questions, please let me know.

**Comment by averyrobbins1** [comment]
Sorry for the late reply! That fixed it. Thank you very much. If I wanted
to do that for other pages, could I do this:

{{ if ne .Permalink "<urls of your about page>" }}

{{ if ne .Permalink "<urls of other page>" }}

    {{ template "_internal/disqus.html" . }}
{{ end }}

Thank you again.

**Comment by averyrobbins1** [comment]
Nevermind I got this to work:

{{ if ne .Permalink "<url1>" | and (ne .Permalink "<url2>") }}
    {{ template "_internal/disqus.html" . }}
{{ end }}

I think information like this would be useful in your readme. Just a
thought!

**Comment by ertuil** [comment]
Thanks. But it is not allowed by Hugo‘s grammar. You can refer to hugo documents.

在 2020年5月10日，02:42，Avery Robbins <notifications@github.com> 写道：

﻿

Nevermind I got this to work:

{{ if ne .Permalink "<url1>" | and (ne .Permalink "<url2>") }}
{{ template "_internal/disqus.html" . }}
{{ end }}

I think information like this would be useful in your readme. Just a
thought!
