### ISSUE TITLE
Upgrade to MathJax 3.0.5

### ISSUE THREAD

**Issue by lloydroc** [ertuil/erblog#17]
Hello can we update MathJax? It seems to look fine on desktop but on mobile the matrix doesn't look ok. I'm hoping upgrade will fix. 

If possible are there some instructions on how to upgrade we can put in README? Put them here and I can make a PR for it.

**Comment by ertuil** [comment]
Thanks. Mathjax 3.0.0 is located in `static/Mathjax-3.0.0` and it is included by `layouts/partials/head.html` line 35 - 40.

**Comment by lloydroc** [comment]
I see that but is it as simple as downloading new version in the static
folder and changing the head partial?

/Lloyd

**Comment by lloydroc** [comment]
Seems like we could also think about not having MathJax checked into this repo and so something like this:

```
     {{ if .Site.Params.MathJax | default true }}
     <!-- adds MathJax support -->
-    <script type="text/javascript" async
-        src="/mathjax-3.0.0/tex-mml-chtml.js">
-    </script>
+    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
     {{ end }}
```

I also really don't like having it included on every single page. Would be great to be able to include it optionally in the front matter.

**Comment by ertuil** [comment]
It is ok, just go ahead.
I did not use a CDN because I thought it doesn't work well in Mainland China. Since so many people are using this theme now, it may be better to use a CDN. (I will do the same thing to other third-party dependencies soon).

However, I am not sure how to include Mathjax when needed.

**Comment by lloydroc** [comment]
Thanks. Did confirm 3.0.5 fixes some major issues that I had. Would be nice
to upgrade it.

/Lloyd

**Comment by ertuil** [comment]
I am now using jsdelivr as CDN. See commit 025703e86d3a595a2c7faded1c875da3d15b6b37.

**Comment by lloydroc** [comment]
Super! I like it.

**Comment by ertuil** [comment]
Now I have figured out how to import `Mathjax` on demand. Please refer out `CHANGELOG.md` and `README.md`. Because it may not be compatible with former settings.

**Comment by lloydroc** [comment]
Thanks I will give it a try. That's a great feature! So nice to only enable
it per page not per site.
