### ISSUE TITLE
Wrong command displayed on the website

### ISSUE THREAD

**Issue by p-daemon** [ertuil/erblog#2]
## Steps to reproduce

1. Go to https://themes.gohugo.io/erblog/ Erblog Hugo Theme 
2. Scroll down to see the **Installation** step
![image](https://user-images.githubusercontent.com/42153231/72303086-b5bcbf80-369e-11ea-844e-7ffa7dc267cd.png)
The command should be `$ git submodule update --remote themes/erblog`

Note: The README.md also displays the same error.

**Comment by ertuil** [comment]
Thanks. I have fixed it in `readme.md`. But it takes some time to sync to [https://themes.gohugo.io/erblog/]( https://themes.gohugo.io/erblog/).
