### ISSUE TITLE
Unable to push to repository

### ISSUE THREAD

**Issue by lloydroc** [ertuil/erblog#20]
Hello are there some permissions that were disabled where we cannot push branches and create PRs? I keep getting this:

```
$ git push --set-upstream origin minor-changes
remote: Permission to ertuil/erblog.git denied to lloydroc.
fatal: unable to access 'https://github.com/ertuil/erblog.git/': The requested URL returned error: 403
$
```

**Comment by ertuil** [comment]
You do not have premission to write this repo directly.
You should push to your cloned repo and create a PR which is welcome.

**Comment by lloydroc** [comment]
Hello I am just trying to push to my feature branch then make a PR to
master. I should have permission for that right?

**Comment by ertuil** [comment]
You are allowed to push to your OWN repo not this repo . Then you can make a PR to send the changes from your repo to this repo.
You can not push to this repo directly because you are not the onwer of this repo.
May be you should check whether  your 'git remote' settings are correct. Or you might refer to github documents.

**Comment by lloydroc** [comment]
Hello @ertuil do you mean branch above? I should have permission to clone this repository, make a feature branch off master, push the feature branch, and create a PR correct? I have done a PR before on this repo doing these steps above?

It seems to be failing when I try to create a branch on the origin.

```
$ git push origin minor-changes
remote: Permission to ertuil/erblog.git denied to lloydroc.
fatal: unable to access 'https://github.com/ertuil/erblog.git/': The requested URL returned error: 403
$
```

I'm basically following these steps. https://gist.github.com/vlandham/3b2b79c40bc7353ae95a

**Comment by ertuil** [comment]
Let me explain it with more details and that might help you.
1. You do not have permission to ertuil/erblog.git.
2. You might clone ertuil/erblog.git into lloydroc/erblog.git and you will have full permissions to your own repo.
3. You might set your origin to lloydroc/erblog.git and push to your own repo.
4. Now, you can pull request to send your contributions from your repo to this repo.
That is the PR workflow, and you might want to have a try, Thanks.
