### ISSUE TITLE
Some advice about code blocks

### ISSUE THREAD

**Issue by JIeJaitt** [ertuil/erblog#21]
This is a really great theme, thanks for all your hard work! How can I make the code block shrink as the screen shrinks so that it won't look too bad to read on a small screen (mobile phone). Also, if possible, I would like to add some small functions to the code block such as copying, displaying the code block name, etc., which will make it look more modern. If possible, I hope he is a mac-style window, so it looks more beautiful! Thank you again for your hard work, erblog is really a great theme, I hope to get your help with my problem.

**Comment by ertuil** [comment]
The code block is rendered by the default Hugo markup renderer, and erblog uses the `markdown.min.css` to generate the styles.

For Q1, I do not confirm the problem you are facing, but maybe you can try to do some tricks in `markdown.min.css` that may fix your problem.
For Q2 and Q3, I currently have no knowledge about the modules to implement the functions you suggested that can still be compatible with Hugo markdown render.

If you have any further questions or suggestions, it is welcome!

**Comment by ertuil** [comment]
Unfortunately, the markdown renderer generates the code blocks into HTML codes (specifically,  ``<pre>...</pre>`` blocks), rather than in an image style. It might be a little difficult to implement your suggestions.

Again, it is welcome to receive any further questions or suggestions from you.

**Comment by JIeJaitt** [comment]
> The code block is rendered by the default Hugo markup renderer, and erblog uses the `markdown.min.css` to generate the styles.
> 
> For Q1, I do not confirm the problem you are facing, but maybe you can try to do some tricks in `markdown.min.css` that may fix your problem. For Q2 and Q3, I currently have no knowledge about the modules to implement the functions you suggested that can still be compatible with Hugo markdown render.
> 
> If you have any further questions or suggestions, it is welcome!

Thanks for the ideas, I think I've got some ideas, I'll get back to you again if I need help.

**Comment by JIeJaitt** [comment]
hi @ertuil , sorry to bother you. This is my first time using hugo, and I have encountered two problems that make me feel tricky.

My site: https://jiejaitt.pages.dev/

- Q1: My website now has two articles, but when I click into the posts menu, only the first article is displayed!
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/77219045/208692128-0d5c39a4-20d3-401a-a9ea-86b49e37399e.png">

- Q2: When I click on the two menus of posts and about, the upper menu bar will disappear, leaving only the current menu, but the menu zone will not be like this, I don't know what happened...
<img width="654" alt="image" src="https://user-images.githubusercontent.com/77219045/208692279-82d83e03-09d7-4ee5-a788-8f8a95332785.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/77219045/208692397-76b1a04a-965e-48a2-94ce-f0afa4564b92.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/77219045/208692485-5ef294e1-b870-4bb1-92b7-09d686e36d80.png">

**Comment by JIeJaitt** [comment]
> Unfortunately, the markdown renderer generates the code blocks into HTML codes (specifically, `\<pre\>...\</pre\>` blocks), rather than in an image style. It might be a little difficult to implement your suggestions.
> 
> Again, it is welcome to receive any further questions or suggestions from you.

hi,sorry to bother you.  did you hear my question? I'm worried you didn't receive？
