### ISSUE TITLE
mathjax error

### ISSUE THREAD

**Issue by progressify** [ertuil/erblog#4]
For mathjax library, you have used a CDN
I receive some error in console relative to mathzoom.js and mathmenu.js
I have resolved to download mathjax from GitHub and including them in my project. Please control this problem in your version of the template.

**Comment by ertuil** [comment]
I use `bootcdn` ( A CDN provided by Chinese Bootstrap Website) which may be unusable in your location. I will fix it soon. 
Thanks.

**Comment by progressify** [comment]
Ty for the update.
Now I revert my version and check if the error is fixed

**Comment by ertuil** [comment]
Hello, I am wondering if this bug has been fixed now?

**Comment by progressify** [comment]
Yes it's ok!
Ty
