### ISSUE TITLE
jQuery support

### ISSUE THREAD

**Issue by progressify** [ertuil/erblog#6]
Hi 
for jQuery support, I must include it externally? With a CDN or I must add the library in static files?
Or layui natively support jQuery? 
Sorry but I don't be able to find English docs for layui

![image](https://user-images.githubusercontent.com/11472632/74604125-5a298b80-50bb-11ea-8b21-d59d5a238144.png)

**Comment by ertuil** [comment]
`Layui.js` uses `jquery.js` as an internal module and it is not exported to globe scope. So there are two ways to use `jquery.js`:

1. import `jquery.js` externally, both CDN or static files should work. You can put a `<script />` in `/layouts/partials/self-define-head.html`.
2. Just `var $ = jQuery = layui.jquery;` to export jquery globally.

**Comment by progressify** [comment]
ok, this line works:
```var $ = jQuery = layui.jquery;```
but the version of jquery is too old: 1.12.3

I have installed a new version of jquery putting that in static files and including that in the head of the template. 
Ty
